all: example1

example1:
	g++ example1.cpp ../console/rectangle.cpp ../console/imageMap.cpp ../console/point.cpp ../console/utils.cpp -o example1.o -std=c++11

run1:
	./example1.o

clean:
	rm -rf *.o
